export const poems=[
    "one day you gonna run free?",
    "dynamics is your best friend ",
    "feeling sad try running looking at sky backwards,",
    "i don't care if i die today or now",
    "it's nice to have a friend",
    "where is my mind?",
    "i wish i could do what my heart wants,okeiy divert you can't,may be one day",
    "why do fireflies die so fast,may be they don't want to live long",
    "A valley and above it forests ,above it clouds and stars ",
    "Crooked laugh,phosphenes of eyes",
    "In a portal where there is no I",
    "glass half empty kinda girl",
    "sun of stars,gradient dirt,aacross the atmosphere",
    "scars forever shining",
    "A wildflower",
]